version: 2.1.{build}
os: Visual Studio 2015
clone_folder: C:\projects\ibex-lib
test: off
configuration:
    - Release
    # - Debug
branches:
  only:
    - pyIbex_version_v3
environment:
  matrix:
    # - CMAKE_PLATFORM: "Visual Studio 14 2015"
      # PYTHON_DIR: "C:\\Python34"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      # PYTHON_DIR: "C:\\Python34-x64"

build_script:
  - echo %PATH%
  - "ls C:/Program\ Files\ (x86)/CMake/bin"
  - "C:/Program\ Files\ (x86)/CMake/bin/cpack.exe -G ZIP" 
  - echo Running cmake...
  - cd c:\projects\ibex-lib
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% PACKAGE.vcxproj
  - CPack.exe -G ZIP


artifacts:
- path: build\ibex-lib*.exe
  name: ibex-lib
- path: build\ibex-lib*.zip
  name: ibex-lib-zip

deploy:
  release: ibex-lib-v$(appveyor_build_version)
  description: 'Custom ibex version for pyIbex and Robotics'
  provider: GitHub
  auth_token:
    secure: kfuelei+usQrQv/IZnoepVAx6SU1E8BKoR6rXwXM3grYnvzBQM2P9xMKQ+Nc+BYr
  artifact: ibex-lib,ibex-lib-zip
  draft: true
  prerelease: false
  on:
    branch: pyIbex_version_3      # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only