version: build{build}
image: Visual Studio 2015
clone_folder: C:\projects\ibex-lib
test: off
configuration:
    - Release

environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      CPACK_PATH: 'C:\\Program Files (x86)\\CMake\\bin'
      platform: x86
      CPPUNIT_DIR: C:\tools\vcpkg\installed\x86-windows
      LP_SOLVER: 'none'
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      CPACK_PATH: 'C:\\Program Files (x86)\\CMake\\bin'
      platform: x64
      CPPUNIT_DIR: C:\tools\vcpkg\installed\x64-windows
      LP_SOLVER: 'none'
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      CPACK_PATH: 'C:\\Program Files (x86)\\CMake\\bin'
      platform: x64
      LP_SOLVER: 'soplex'
      CPPUNIT_DIR: C:\tools\vcpkg\installed\x64-windows

init:
    - cmd: vcpkg cache
cache:
    - C:\tools\vcpkg\installed\
install:
    - vcpkg install cppunit:"%platform%"-windows
    - choco install winflexbison

build_script:
  - echo Running cmake...
  - cd c:\projects\ibex-lib
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_BUILD_TYPE=Release -DLP_LIB=%LP_SOLVER% -DINTERVAL_LIB=filib -DCPPUNIT_DIR="%CPPUNIT_DIR%" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% PACKAGE.vcxproj
  - msbuild %MSBuildOptions% CHECK.vcxproj
  - set PATH=%CPACK_PATH%;%PATH% # conflit with choco pack alias. need to put cpack.exe first
  - CPack.exe -G NSIS
  - CPack.exe -G ZIP

artifacts:
- path: build\ibex*.exe
  name: ibex-lib
- path: build\ibex*.zip
  name: ibex-lib-zip


deploy:
  release: ibex-lib-v$(appveyor_build_version)
  description: 'ibexlib compiled without lp solver'
  provider: GitHub
  auth_token:
    secure: Bu9kqyFD6errPkHu23iueJXI5x7JZ/8ZHVwoYNB1ZijEQ7KOySfC/sJ0fKBDgFOA

  artifact: ibex-lib,ibex-lib-zip
  draft: true
  prerelease: false
  on:
    # branch: msvc_release_test      # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
